name: DuckyPanel Docker Image CI

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'docker-files/ducky-panel'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker-files/ducky-panel'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
      name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
      name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
      name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
      name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker-files/ducky-panel
          tags: ahhf/ducky-panel:k8s-mail-host
