name: Rspamd Docker Image CI

on: 
  push:
    branches:
      - 'main'
    paths:
      - 'docker-files/rspamd'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker-files/rspamd'
  workflow_dispatch:

env:
  VERSION: 3.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker-files/rspamd
          tags: ahhf/rspamd:$VERSION
          build-args: version=$VERSION
